namespace ReactNativeWebView2{
    [default_interface]
    runtimeclass ReactWebView2 : Windows.UI.Xaml.Controls.UserControl{
        ReactWebView2(Microsoft.ReactNative.IReactContext context);
        void NavigateToHtml(String html);
    };
} // namespace ReactNativeWebView2